using System;
using System.Security.Cryptography;
using System.Text.Json.Nodes;
using ByJP.AtprotoGaming.Core;
using ByJP.AtprotoGaming.Core.Signing;
using Xunit;

namespace ByJP.AtprotoGaming.Core.Tests;

public class SigningTests
{
    // A P-256 keypair generated by the BCL, expressed as the inputs our code
    // consumes (a private did:key) and the values we cross-check against.
    private sealed record TestKey(string PrivateDidKey, byte[] D, byte[] Qx, byte[] Qy);

    private static TestKey NewKey()
    {
        using var ec = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var p = ec.ExportParameters(includePrivateParameters: true);
        var d = Pad32(p.D!);
        var qx = Pad32(p.Q.X!);
        var qy = Pad32(p.Q.Y!);

        var prefixed = new byte[2 + 32];
        prefixed[0] = 0x86; prefixed[1] = 0x26; // P-256 private multicodec
        Buffer.BlockCopy(d, 0, prefixed, 2, 32);
        var didKey = "did:key:z" + Base58Btc.Encode(prefixed);
        return new TestKey(didKey, d, qx, qy);
    }

    private static byte[] Pad32(byte[] b)
    {
        if (b.Length == 32) return b;
        var r = new byte[32];
        Buffer.BlockCopy(b, 0, r, 32 - b.Length, b.Length);
        return r;
    }

    [Fact]
    public void DerivesPublicPointMatchingTheBcl()
    {
        var key = NewKey();
        var (x, y) = P256.MultiplyG(key.D);
        Assert.Equal(Hex.Of(key.Qx), Hex.Of(x));
        Assert.Equal(Hex.Of(key.Qy), Hex.Of(y));
    }

    [Fact]
    public void SignedRecordCidAndSignatureVerify()
    {
        var key = NewKey();
        var signing = SigningKey.FromDidKey(key.PrivateDidKey, "test.game.record#attestation");
        var signer = new RecordSigner(signing);

        const string repoDid = "did:plc:exampleexampleexample";
        var record = new JsonObject
        {
            ["$type"] = "test.game.record",
            ["value"] = 42,
            ["nested"] = new JsonObject { ["k"] = "v" },
        };

        signer.Sign(record, repoDid);

        var signatures = Assert.IsType<JsonArray>(record["signatures"]);
        var att = Assert.IsType<JsonObject>(signatures[0]);

        // The published key in the attestation is the derived public did:key.
        Assert.Equal(signing.PublicDidKey, att["key"]!.GetValue<string>());

        // Recomputing the content CID from the (signed) record + attestation
        // metadata reproduces the cid stored in the attestation.
        var cidBin = ContentCid.ComputeBinary(record, att, repoDid);
        Assert.Equal(Cid.ToStringForm(cidBin), att["cid"]!.GetValue<string>());

        // The signature verifies against the published key over that CID.
        var sig = Convert.FromBase64String(att["signature"]!["$bytes"]!.GetValue<string>());
        Assert.Equal(64, sig.Length);
        using var verifier = EcdsaP256.CreateVerifier(key.Qx, key.Qy);
        Assert.True(verifier.VerifyData(cidBin, sig, HashAlgorithmName.SHA256));
    }

    [Fact]
    public void SignatureIsLowS()
    {
        var key = NewKey();
        var signer = new RecordSigner(SigningKey.FromDidKey(key.PrivateDidKey, "t#attestation"));
        var record = new JsonObject { ["$type"] = "t", ["n"] = 1 };
        signer.Sign(record, "did:plc:x");

        var att = (JsonObject)((JsonArray)record["signatures"]!)[0]!;
        var sig = Convert.FromBase64String(att["signature"]!["$bytes"]!.GetValue<string>());

        // s (the high 32 bytes) must be <= n/2 after low-S normalization.
        var sHigh = new byte[32];
        Buffer.BlockCopy(sig, 32, sHigh, 0, 32);
        var s = BigIntBytes.FromUnsignedBigEndian(sHigh);
        var n = System.Numerics.BigInteger.Parse(
            "0FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551",
            System.Globalization.NumberStyles.HexNumber);
        Assert.True(s <= (n >> 1));
    }

    [Fact]
    public void RepeatedSignsWithOneKeyAllVerify()
    {
        // The public point is cached on the key after the first use; signing many
        // records must keep producing valid, independently-verifying signatures.
        var key = NewKey();
        var signer = new RecordSigner(SigningKey.FromDidKey(key.PrivateDidKey, "t#a"));
        using var verifier = EcdsaP256.CreateVerifier(key.Qx, key.Qy);

        for (int i = 0; i < 5; i++)
        {
            var record = new JsonObject { ["$type"] = "t", ["i"] = i };
            signer.Sign(record, "did:plc:repo");
            var att = (JsonObject)((JsonArray)record["signatures"]!)[0]!;
            var cidBin = ContentCid.ComputeBinary(record, att, "did:plc:repo");
            var sig = Convert.FromBase64String(att["signature"]!["$bytes"]!.GetValue<string>());
            Assert.True(verifier.VerifyData(cidBin, sig, HashAlgorithmName.SHA256), $"sign #{i} failed to verify");
        }
    }

    [Fact]
    public void NormalizeLowSFlipsHighSLeavesLowSAndPreservesR()
    {
        // Deterministically exercise both branches of low-S normalization (the
        // end-to-end SignatureIsLowS test only hits the high-S path ~50% of runs).
        var n = System.Numerics.BigInteger.Parse(
            "0FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551",
            System.Globalization.NumberStyles.HexNumber);
        var halfN = n >> 1;

        // High-S: s = n-1 (> n/2) → normalized to n-(n-1) = 1; r left intact.
        var high = MakeSig(rFill: 0xAB, s: n - 1);
        InlineAttestation.NormalizeLowS(high);
        Assert.Equal(System.Numerics.BigInteger.One, SOf(high));
        Assert.True(SOf(high) <= halfN);
        Assert.Equal((byte)0xAB, high[0]);
        Assert.Equal((byte)0xAB, high[31]);

        // Low-S: s = 2 (< n/2) → unchanged.
        var low = MakeSig(rFill: 0xCD, s: 2);
        InlineAttestation.NormalizeLowS(low);
        Assert.Equal(new System.Numerics.BigInteger(2), SOf(low));
    }

    private static byte[] MakeSig(byte rFill, System.Numerics.BigInteger s)
    {
        var sig = new byte[64];
        for (int i = 0; i < 32; i++) sig[i] = rFill;
        Buffer.BlockCopy(BigIntBytes.ToUnsignedBigEndian(s, 32), 0, sig, 32, 32);
        return sig;
    }

    private static System.Numerics.BigInteger SOf(byte[] sig)
    {
        var s = new byte[32];
        Buffer.BlockCopy(sig, 32, s, 0, 32);
        return BigIntBytes.FromUnsignedBigEndian(s);
    }

    [Fact]
    public void RoundTripsPrivateDidKeyThroughParse()
    {
        var key = NewKey();
        var signing = SigningKey.FromDidKey(key.PrivateDidKey, "t#a");
        // Deriving again from the parsed key yields a stable public did:key.
        Assert.StartsWith("did:key:z", signing.PublicDidKey);
        Assert.Equal(signing.PublicDidKey,
            SigningKey.FromDidKey(key.PrivateDidKey, "t#a").PublicDidKey);
    }
}
